### ISSUE TITLE
api.hostname can now be a list

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-docs#109]
The docs are here https://flowcrypt.com/docs/technical/enterprise/configuration/general-and-https.html 

Need to update to reflect changes done here https://github.com/FlowCrypt/flowcrypt-email-key-manager/issues/874

"Normal size" deployments generally don't need this feature, but it's good to have it documented that it can in fact be a list, and why.

When it's a list, the first hostname in the list should be the hostname of the service, followed by other hostnames (like hostname of the particular instance).

**Comment by bilalashraf123** [comment]
What is the benefit of having multiple hostnames in `api.hostname` property and then pick the first one? How multiple hostnames will be utilised in one instance?

As per my understanding, it is something we can resolve like this:

- If there is one instance `api.hostname` contains internal FQDN and reverse proxy handles external domain which ultimately maps to internal domain.
- If there are multiple instaances, then still each instance have internal FQDN while load balancer handles the external domain.

**Comment by tomholub** [comment]
I'll forward you the relevant customer email that will give you context

**Comment by bilalashraf123** [comment]
Suggested text to be added in the docs:

**The host where the KACLS will be deployed.**

**For larger deplyments, multiple comma separated hostnames can also be configured. If multiple hostnames are configured, then the first one will be the hostname of the service, while the remaining ones are........ ?**

Can we also say - the first one will be the primary hostname of the service, while the remaining ones are secondary instances ??

Need your input to complete the above text.

**Comment by tomholub** [comment]
The original docs were referring to KACLS which is wrong, it is supposed to refer to all services.

> The host where the the service will be deployed - an IP address or FQDN. Use a comma-separated list if you expect to access the service on more than one domain, in which case the first domain is treated as primary.
