### ISSUE TITLE
add documentation about different postgres privileges

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-docs#110]
// edited by tom

## EKM read/write/update schema user setup:

```sql
-- Run as postgres super user!
CREATE DATABASE flowcrypt;
CREATE USER ekm_su;
CREATE USER ekm_rw;
CREATE USER ekm_ro;
GRANT CONNECT ON DATABASE flowcrypt TO ekm_su;
GRANT CONNECT ON DATABASE flowcrypt TO ekm_rw;
GRANT CONNECT ON DATABASE flowcrypt TO ekm_ro;
CREATE SCHEMA ekm;
GRANT ALL ON SCHEMA ekm TO ekm_su;
GRANT USAGE ON SCHEMA ekm TO ekm_ro;
GRANT USAGE ON SCHEMA ekm TO ekm_rw;
ALTER USER ekm_su SET search_path to 'ekm';
ALTER USER ekm_rw SET search_path to 'ekm';
ALTER USER ekm_ro SET search_path to 'ekm';

-- Run as ekm_su!
GRANT SELECT ON ALL TABLES IN SCHEMA ekm TO ekm_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA ekm GRANT SELECT ON TABLES TO ekm_ro;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ekm TO ekm_rw;
GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA ekm TO ekm_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA ekm GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ekm_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA ekm GRANT SELECT, UPDATE ON SEQUENCES TO ekm_rw;

```

## WKD read/write/update schema user setup:

```sql
-- Run as postgres super user!
CREATE DATABASE flowcrypt;
CREATE USER wkd_su;
CREATE USER wkd_rw;
CREATE USER wkd_ro;
GRANT CONNECT ON DATABASE flowcrypt TO wkd_su;
GRANT CONNECT ON DATABASE flowcrypt TO wkd_rw;
GRANT CONNECT ON DATABASE flowcrypt TO wkd_ro;
CREATE SCHEMA wkd;
GRANT ALL ON SCHEMA wkd TO wkd_su;
GRANT USAGE ON SCHEMA wkd TO wkd_ro;
GRANT USAGE ON SCHEMA wkd TO wkd_rw;
ALTER USER wkd_su SET search_path to 'wkd';
ALTER USER wkd_rw SET search_path to 'wkd';
ALTER USER wkd_ro SET search_path to 'wkd';

-- Run as wkd_su!
GRANT SELECT ON ALL TABLES IN SCHEMA wkd TO wkd_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA wkd GRANT SELECT ON TABLES TO wkd_ro;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA wkd TO wkd_rw;
GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA wkd TO wkd_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA wkd GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wkd_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA wkd GRANT SELECT, UPDATE ON SEQUENCES TO wkd_rw;
```

Once the *_su users (super users) are created and have all privileges to a schema they take over and do all of the work.  The reason for that is if they don't then newly created tables won't trigger the default privileges.

https://stackoverflow.com/questions/760210/how-do-you-create-a-read-only-user-in-postgresql

I'll try it out a bit later if you want.   Code schema generation would need to be done with the *_su user.

_Originally posted by @Jerbell in https://github.com/FlowCrypt/flowcrypt-email-key-manager/issues/872#issuecomment-779644778_

**Comment by bilalashraf123** [comment]
Can I have more context before adding these in the docs? e.g. 

- what requirements/use cases are we trying to cover by adding these privileges in docs?
- Ultimatey, only one user can be configured in EKM/WKD. How multiple users with different privileges will behave?
- Do you mean e.g. on the very first start of the service, we need high privilege user, because it needs to create tables in DB. Later we change the user with only RW privilege and so on?

**Comment by Jerbell** [comment]
>     * Ultimatey, only one user can be configured in EKM/WKD. How multiple users with different privileges will behave?

There would be separate servers for `_rw` and `_ro`, with different properties.  Which would equate to read/write or read only servers.  This is more of an example setup for a company that wants this split, but I imagine a lot wouldn't want this split between users, just one user.

**Comment by Jerbell** [comment]
>     * Do you mean e.g. on the very first start of the service, we need high privilege user, because it needs to create tables in DB. Later we change the user with only RW privilege and so on?

The requirement was for a user (*_su) to create/modify tables.  If the postgres (root) user executes the `ALTER DEFAULT PRIVILEGES ` then these default privileges will only be granted when postgres creates the tables.  So the _su user needs to execute the `ALTER DEFAULT PRIVILEGES ` commands, so that when they (_su user) creates the tables, priviliges are granted to the corresponding _ro and _rw users accordingly.  Does that make sense?

**Comment by tomholub** [comment]
> what requirements/use cases are we trying to cover by adding these privileges in docs?

As Julian said - usually customers don't care and want to have a single user. That should be thepreferred way, in the docs as well. We should recommend to our users that the default way is single read/write/schemachange user (all privileges on the relevant schema).

We have one customer who are very particular in how they want to deploy, and want read instance separate from write instances. Read instances then only have read privileges for postgres users. We would like to document this, but as an alternative, not the default choice.

**Comment by bilalashraf123** [comment]
Draft pull request to check the contents and arrangements.

https://github.com/FlowCrypt/flowcrypt-docs/pull/123
