### ISSUE TITLE
remove dated issues from known limitations

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-docs#125]
1) These two are the same issue and they have been resolved:

![image](https://user-images.githubusercontent.com/6306961/111709150-0699ec00-883f-11eb-8d6b-66e1b887da2e.png)

2) this "Forwarded messages to include attachments" I imagine we already implemented - please test / confirm

**Comment by seisvelas** [comment]
> These two are the same issue and they have been resolved:

Sorry, that was my editing mistake from so time ago

> this "Forwarded messages to include attachments" I imagine we already implemented - please test / confirm

You're correct, this works just fine now
