### ISSUE TITLE
document various ways to set properties - file, sysarg, env var

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-docs#138]
You can pass in a password as a env variable or as a command line argument though - doesn't have to be a property. 

_Originally posted by @Jerbell in https://github.com/FlowCrypt/flowcrypt-enterprise-on-prem/issues/1129#issuecomment-825314978_

We should document this in https://flowcrypt.com/docs/technical/enterprise/configuration/general-and-https.html - so it should look like this:

> # On-prem general configuration and HTTPS
>
> This page applies equally to all of our on-prem server-side apps.
>
> ## How to set properties
>
> Each property can be set either in properties file, as a sysarg or an environment variable, as follows:
>
> ... [add info here]
>
> ## General properties
>
> General properties relating to basic configuration and how the app REST API and/or web app is accessed.

**Comment by Jerbell** [comment]
It's in the README, though I guess it should be in each of the docs too?

## Property definition order
Properties are defined in the following order (from lowest to highest precedence):

- Properties file (`--config application.properties`)
- Environment variables - use capitals and underscores (`ORG_ID=Tesla java -jar app.jar`)
- Command line arguments (`java -jar app.jar --property org.id=Tesla`)
- Code (internal only) there is an internal map on the `Props.loadProps` method

**Comment by tomholub** [comment]
This is enough for me - I'll put it in a single place in public docs: https://flowcrypt.com/docs/technical/enterprise/configuration/general-and-https.html since customers don't get the readme
