### ISSUE TITLE
idea: Tom's Story

### ISSUE THREAD

**Issue by prep-gh** [FlowCrypt/flowcrypt-docs#35]
@tomholub 
I have an idea

There should be a "Tom's Story" doc or blog article, 
that documents WHY you did this, how you got to this point, and maybe some futures' thoughts. 

An icon or a thumbnail on the main page points to this with a <sub> more...</sub> or <sub> &lt; &lt;more&gt;&gt;</sub> 

So instead of one liner feelings everywhere, where we know you are trying to communicate these things -- one, discrete write-up of "the vision" and how you got to the present.

It helps people "know" FlowCrypt through Tom's eyes and this is where all of the "Here's why I did it"  and "please understand that this is very much an ongoing process" thoughts would go.

It could be written from an "I" first-person context or a biographical context.

I can give you a template for this, if desired.

**Comment by tomholub** [comment]
A valid idea, but I'm not entirely sure I want it. I don't want to promote myself all that much. I'll go ahead and make a milestone for "to think about"

**Comment by tomholub** [comment]
Anyway this one would probably go in the web, not docs. So I'll go ahead and close it here.
