### ISSUE TITLE
Known Limitations page outdated (limitations appear to have been overcome)

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-docs#48]
The [Known Limitations](https://flowcrypt.com/docs/technical/limitations.html) page features a few functionalities marked 'planned soon':

![planned](https://user-images.githubusercontent.com/44826516/86199858-d11e6880-bb20-11ea-9b5d-08dcc5a799b8.png)

However, clicking the links to the GitHub issues, all appear to be closed and implemented. Here are the issues:

https://github.com/FlowCrypt/flowcrypt-browser/issues/1080
https://github.com/FlowCrypt/flowcrypt-browser/issues/668
https://github.com/FlowCrypt/flowcrypt-browser/issues/873

Should these be removed from the known limitations page?

**Comment by tomholub** [comment]
Yes, and you can change `Cannot replace primary private key without reinstalling plugin` to planned soon. Thanks for noticing!
