### ISSUE TITLE
Add index page for flowcrypt.com/docs/technical/

### ISSUE THREAD

**Issue by seisvelas-test** [FlowCrypt/flowcrypt-docs#56]
Here is what flowcrypt.com/docs/technical/ currently serves:

![Screenshot_2020-07-09_15-59-14](https://user-images.githubusercontent.com/66458838/87090253-47942800-c1fd-11ea-82fb-8e6abfc5383d.png)

Aside from being ugly, it's also not helpful. I found this because I wanted to look at one of our technical documentation articles, and I expected to be able to access the little documentation sidebar. 

Ideally, this page would have some simple text with links to our technical documentation, or just a brief message of some kind and the normal docs layout, so users can access the documentation they're looking for via the sidebar.

**Comment by seisvelas** [comment]
Sorry! @seisvelas-test is an account I use to test for GitHub related security issues. Occasionally I want to do things that might make my account vulnerable (like disabling 2FA) when trying to explore a possible attack vector, so it's safest to have a separate account just for that purpose.

Today I was learning about subdomain takeover via GitHub pages and forgot to switch back to my main account. Woops!

This is a good time to note that no privileges should ever be provided to @seisvelas-test and never assume that account is not compromised. I try every crazy idea that occurs to me with that account.
