### ISSUE TITLE
Require pass phrase to decrypt option in docs does not appear in extension

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-docs#59]
From support email: https://mail.google.com/mail/u/5/#inbox/FMfcgxwJWrjVcrnLnKsqZDSmLHGRnGbb

Here are the docs for requiring a passphrase to decrypt: https://flowcrypt.com/docs/guide/common-tasks/require-pass-phrase.html

According to those docs, you can go FlowCrypt Settings -> Security -> Require Pass Phrase to open encrypted email
and see the following options:

![](https://flowcrypt.com/docs/assets/images/screenshots/browser/requiretoenterpassphrasetoread/gotosecurity.png)

However, in the real menu presented by the extension, the option 'Require Pass Phrase to open encrypted email' does not appear. Here is what I get:

![Screenshot_2020-07-22_13-03-14](https://user-images.githubusercontent.com/44826516/88211740-c0db4400-cc1b-11ea-9fbd-dae1b36720cf.png)

Should the docs instead be directing users to select the 'Forget stored pass phrases' option?

**Comment by tomholub** [comment]
> Should the docs instead be directing users to select the 'Forget stored pass phrases' option?

Good observation, yes!
