### ISSUE TITLE
clearer docs on where private keys are stored

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-docs#74]
>(uninstall feedback) Even checking the FAQ and rare questions I couldn't quite find out if my private key will be safe, i.e. stay on my machine, or if I actually upload it to flowcrypt servers. I have to assume the latter so I won't use it.

Ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwJXxnSZcKXHfXjRDCWZfwSvkss

**Comment by seisvelas** [comment]
There have been other emails where I've explained to users that private keys aren't stored on our servers, so perhaps this should be communicated better in the docs.

**Comment by tomholub** [comment]
We have an excerpt from our privacy policy in "old" knowledge base

https://duckduckgo.com/?t=canonical&q=where+are+flowcrypt+private+keys+stored&ia=web

We could move it to the docs, reword a bit so it's not just an excerpt from the privacy page, and then redirect this url there.

**Comment by tomholub** [comment]
But actually, we do have this described in detail here https://flowcrypt.com/docs/technical/manage-private-keys.html

Maybe we just need a new Q/A item specifically with that question, that has a two-liner response and links to https://flowcrypt.com/docs/technical/manage-private-keys.html and the privacy policy

**Comment by seisvelas** [comment]
I think the problem for users is where this page is found in the docs navigation menu. It's under "Consumer and Small Business". I personally would not think to look for it there, and to confirm my hunch, I asked my wife to try to find the section about managing private keys from the docs menu and, just like the user who provided the feedback, her intuition was to check the FAQ.

"Consumer and Small Business" is logically a fitting name, because regular users are indeed "Consumers". But intuitively, I don't think people see that section and identify like "Ah, I'm a consumer, I should check this section". It's hard to articulate why but I feel like the naming of that section actually diverts the demographic it's intended to target (other than small businesses, for them that's probably the first place they check for anything)

In any case, I've made a PR to add this to the FAQ. In the meantime, I'll try to think of better name ideas for that section :)

**Comment by tomholub** [comment]
I know what you mean. Could we fix this by just renaming it? `Regular users?`
