### ISSUE TITLE
improve docs to answer these customer questions

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-docs#88]
> (enterprise) How do users access the local app/web app? Can it be SSO enabled?

Local app uses Google oAuth2 for Gmail permissions.
Google OIDC token used to authenticate with backend or with your on-prem services. You can have 3rd party SSO flow enabled in google which some of our customers have.

> (enterprise) Is there an admin console? What functionality is available? How are access rights controlled?

Enterprise Admin Panel (EAP) is only available for on-prem deployments. You use it to manage keys. There is only one privilege user type: admin. List of admins is configured in a properties file, and admins are authenticated using your own (non-Google) IdP, if you have one, over OIDC.
(a more fine-grained privilege model is planned for Q4 2021 which will use JWT claims in the ID token received to differentiate user privileges)

All of EAP features revolve around managing keys: viewing info about users, keypairs, user-keypair relationships, exporting private keys, taking actions on keys like revoking them, and automatic functionality (EAP Orchestrator) which take care of key lifecycle from generation, rotation or extension, expiration etc.

> (general) Storage of the private keys on Local App - is there any inherent encryption functionality to protect the key while stored?

This depends on the platform.
 - Chrome extension: private keys can be passphrase protected (this is configurable) with a pass phrase kept in session.
 - Android App: Android Keychain provides an encryption key which is used to AES256 encrypt private keys in local SQLite database (only particularly sensitive fields encrypted like private keys, access tokens, message cache)
 - iOS App: similar iOS-specific mechanism except this uses an encrypted local Realm database (the whole db is encrypted)

Further, you should use full disk encryption on all user devices.

**Comment by bilalashraf123** [comment]
> > (enterprise) How do users access the local app/web app? Can it be SSO enabled?
> 
> Local app uses Google oAuth2 for Gmail permissions.
> Google OIDC token used to authenticate with backend or with your on-prem services. You can have 3rd party SSO flow enabled in google which some of our customers have.

[Bilal] I assume here we are talking about FlowCrypt Plugin. As per my knowledge, plugin uses Google OIDC IDP to get JWT which then uses to access user inbox emails and other operations using gmail API. What you mean by 3rd party SSO Flow? Do Google OIDC uses as a proxy, which delegates authentication to other IDP? If yes, please share the 3rd party SSO link. Thanks.

> Chrome extension: private keys can be passphrase protected (this is configurable) with a pass phrase kept in session.

[Bilal] We currently have this page i.e. https://flowcrypt.com/docs/technical/manage-private-keys.html

Do we have existing docs for Android and iOS app?

**Comment by tomholub** [comment]
> What you mean by 3rd party SSO Flow? Do Google OIDC uses as a proxy, which delegates authentication to other IDP? If yes, please share the 3rd party SSO link. Thanks.

Yes, the google login screen will just ask you for email but not for password. Then forward you to configured IdP to actually log in. Any OIDC IdP will work, we tried it with OneLogin and Auth0. After you authenticate there, it forwards back to google, which trusts that provider for your domain and then issues OIDC JWT for the end up (in our case browser extension but customers tend to have such flow company wide, for apps that only integrate with Google, such as currently our client apps).

**Comment by tomholub** [comment]
> Do we have existing docs for Android and iOS app?

No - we should start writing them. I like how for example here https://www.cockroachlabs.com/docs/v20.2/install-cockroachdb-linux they let you switch between platforms or approaches for many pages of the docs, we should do something similar but for desktop browser / iOS / Android.

**Comment by bilalashraf123** [comment]
> > (enterprise) How do users access the local app/web app? Can it be SSO enabled?
> 
> Local app uses Google oAuth2 for Gmail permissions.
> Google OIDC token used to authenticate with backend or with your on-prem services. You can have 3rd party SSO flow enabled in google which some of our customers have.

A new element with the name `Authentication` added under `GETTING STARTED > Install FlowCrypt`.

> > (enterprise) Is there an admin console? What functionality is available? How are access rights controlled?
> 
> Enterprise Admin Panel (EAP) is only available for on-prem deployments. You use it to manage keys. There is only one privilege user type: admin. List of admins is configured in a properties file, and admins are authenticated using your own (non-Google) IdP, if you have one, over OIDC.
> (a more fine-grained privilege model is planned for Q4 2021 which will use JWT claims in the ID token received to differentiate user privileges)
> 
> All of EAP features revolve around managing keys: viewing info about users, keypairs, user-keypair relationships, exporting private keys, taking actions on keys like revoking them, and automatic functionality (EAP Orchestrator) which take care of key lifecycle from generation, rotation or extension, expiration etc.

It is already available under https://flowcrypt.com/docs/technical/enterprise-server/latest/enterprise-server.html and https://flowcrypt.com/docs/technical/email-key-manager/latest/email-key-manager.html



> Chrome extension: private keys can be passphrase protected (this is configurable) with a pass phrase kept in session.

This is already available under https://flowcrypt.com/docs/technical/manage-private-keys.html



> * Android App: Android Keychain provides an encryption key which is used to AES256 encrypt private keys in local SQLite database (only particularly sensitive fields encrypted like private keys, access tokens, message cache)
> 
> * iOS App: similar iOS-specific mechanism except this uses an encrypted local Realm database (the whole db is encrypted)

Separate issue https://github.com/FlowCrypt/flowcrypt-docs/issues/117 is created for this.
