### ISSUE TITLE
Browser default encryption algo incorrectly claimed to be 2048bit RSA on /docs/technical/security.html

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-docs#91]
When in fact, the browser offers a choice between 2048bit RSA, 4096bit RSA, and ECC Curve25519. Among these, the default option is ECC Curve25519.

Not sure if this doc is just outdated, if so let me know and I'll update it.

ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwKjBNljzJNzBhXPqzqXVFlnkld

**Comment by tomholub** [comment]
Yup the doc is old. If the docs don't mention this, you can add that enterprises get to choose their preferred default.
